# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/liquibase_db
spring.datasource.username=postgres
spring.datasource.password=Bubbly12@
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
